### ISSUE TITLE
play low latency audio

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#100]
the goCue has a perceivable delay wrt onset of the visual stimulus. this may be caused by the default driver.

https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/low-latency-audio

**Comment by anne-urai** [comment]
@sanworks what would you recommend?

**Comment by anne-urai** [comment]
Why was this closed? Should we test different drivers and measure the latency of the onset sound?

@nbonacchi would be good to know if the task settings specify a 0 second delay between visual and sound onset (I believe there was a delay coded in some previous version of the task) - we want this to be a true RT task.

**Comment by nbonacchi** [comment]
@anne-urai It was closed because the low latency using the ASIO drivers is alredy implemented, also its related to #112. I don't think we are going to test sound latencies more than what @sanworks already has. Furthermore, I'm sure that there is no time to change whatever we have working atm. 

If you want to measure the latency it should be the difference between the goCueTrigger_times and the goCue_times datasettypes, as soon as [https://github.com/int-brain-lab/ibllib/issues/39](https://github.com/int-brain-lab/ibllib/issues/39) is implemented.

you can define the delay between stimOn and goCue by setting the INTERACTIVE_DELAY parameter in task_settings.py  Since version 3.5.4 it has been set to 0 (it was left at 0.1 for technical reasons which are now fixed)

Please note that one of the parameters of the impulsiveness control algorithm (still working on that [here](https://github.com/int-brain-lab/iblrig/issues/109)) is to increase the interactive delay, so at some point, when I release it, even setting this delay to 0 might not have an effect depending on the mouse.
