### ISSUE TITLE
Interactive delay

### ISSUE THREAD

**Issue by alejandropan** [int-brain-lab/iblrig#112]
Is the interactive delay controlling the timing of  the sound cue? If yes, should this be set to 0? Currently the sound cue appears _after_ the gabor, which I believe is incorrect.

**Comment by nbonacchi** [comment]
The sound is triggered at onset of the closed_loop state
it should be low latency using ASIO drivers, to use the specific xonar sound card config with these drivers please set the SOFT_SOUND flag in task settings to 'xonar' this option will be resetted at every update unless we decide to change the default...
The reason it is not default is because not everyone had the xonar card...

Alternatively I could set xonar as default and fallback on sysdefault warning the user if this happens. 
Or should it break?

(btw, sysdefault is whatever sound driver is selected in windows sound by clicking on the sound in the lower right corner and selecting the output)

**Comment by nbonacchi** [comment]
related to #100

**Comment by anne-urai** [comment]
Shouldn't everyone have the Xonar card in the official rigs? I'd say let's make that the default, and throw a warning when Xonar is not present so that the user can change it to sysdefault.
