### ISSUE TITLE
No visual stim

### ISSUE THREAD

**Issue by alejandropan** [int-brain-lab/iblrig#118]
Error message:

Unhandled Exception: System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Bonsai.Program.Main(String[] args)
   at Bonsai64.Program.Main(String[] args)

**Comment by nbonacchi** [comment]
This exception is not related to the visual stimulus coming up. It is caused by the COM ports not being released gracefully when Bonsai is called without a UI. Although Bonsai properly sends the command to unload and close the connection windows does not interpret this properly. It's a windows bug more than a Bonsai bug and is expected to always appear at the end of the session...
