### ISSUE TITLE
Add black frame around synch square pulse on screen (used by frame2ttl)

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#144]
This will help potentially with 1) increase photosensor sensitivity 2) ensuring the mouse does not see any flickering visual signal.

**Comment by nbonacchi** [comment]
I'm not sure why a black square around a flickering black and white square would help with the mouse not seeing flickering. The sensor should cover the square anyway, there are 2 variables in each task that that allow the user to task the size of the square if needed.

Regarding sensitivity  it should come properly calibrated. Is there a problem with the frame2ttl not logging square changes?

**Comment by GaelleChapuis** [comment]
1) it is not that easy to place the sensor so that the light patch is exactly covered. Adding a black frame around it will help ensuring no mice see any flickering. That will become increasingly important onto the setup for ephys. 

2) we do not know if it is due to sensor gain or screen brightness, but on some rigs the sensor is not able to sense change in the patch of light. We would like to test whether adding a black frame (instead of the grey background) will help.

I do not see a good reason why not to try.

**Comment by anne-urai** [comment]
@sanworks can you elaborate on the rationale behind the black border?

**Comment by nbonacchi** [comment]
While having a black border around the sync square might help with transitions to black as there would be no bleeding of photons from areas not under the sensor, it would most probably, and by the same rationale, do the opposite for transitions to white. The gray surrounding should be neutral as gray is half black and half white.
Do we have any evidence that the transitions to black are the problem?
Also the way I see it this is most probably a threshold problem of the sensor.
The firmware should allow to change it, we can add this to the list of things to do when we calibrate the screen, i.e. find the threshold of the frame2ttl. On the other hand if the sensor is so flaky it's because it's not using the full range or it really requires to be connected to the screen w/o the fresnel lens, maybe we can find a better sensor?
