### ISSUE TITLE
warn the user when a mouse is considered 'untrainable'

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#158]
If after 40 days of training (i.e. 40 days with behavioral data, not 40 days since the beginning of training) the mouse does *not*  have all contrasts introduced, warn the user that the animal can be taken off the IBL protocol

**Comment by nbonacchi** [comment]
I think this is a good idea, the place for it however might be Alyx first and later a check from the rigs ...
I would group this with the is_trained discussion in issue #108
I can keep this issue here like the is_trained one and wait for the Alyx implementation to integrate it in the rig.
Someone should open both issues in Alyx
