### ISSUE TITLE
adding single valve click to release water

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#162]
I think it would be useful to add just option with single valve click to check the water drop. It would be helpful to double check if drop is released by having an option "single valve click". That would allow to click few times between one animal and another instead using flush water (that makes a mess). These option would be very helpful to place in optimal distance water spout (so it is not too far or too low for the animal).

**Comment by nbonacchi** [comment]
The problem with simple valve click is that the calibration of the valve is task dependent and not a global variable. PyBpod does not have a concept of reward, just of valve opening times, it does not even assume that the valve is a water valve it could be an odor, oil, liquid gold, beer or whatever you like really. The whole calibration et al. is because we are delivering water to mice in the range of µl. and we decide that a valve click is between 1 and 3 µl.
What we have planned is an override panel that will trigger outputs with the use of buttons exactly for the purpose of testing the outputs pre-session. Until this is done the FlushWater protocol is supposed to allow you to test the water output and make sure water is coming out. Flush Water will open a valve until you press stop or stop trial.
I could change the protocol to open the valve for something like 0.1 seconds every time you press stop trial. 
Actually you can test it yourself. At the beginning of the file you have the definition for ntrials, valve_on_time, and iti. the default is:
```python
ntrials = 1
valve_on_time = 1000
iti = 0.9
```
This means that the 'session' will have one trial that starts by opening the valve for 1000 seconds after that it would close the vlave for 0.9 seconds before stopping.
Of course ITI never happens as usually people stop the task after they see the water come out.
If you would change the variables like this:
```python
ntrials = 1000
valve_on_time = 0.1
iti = 1000
```
The task would open a valve for 0.1 seconds and then get stuck in the ITI state for 1000 seconds.
This means that if you press the stop trial button it would restart a trial by opening the valve for anothe 0.1 seconds and then getting stuck again in the ITI state. This would go on for 1000 drops, or 1000 stop trials before exiting.
Of course if you want the valve to be open longer you can change the valve_on _time to what you want.

If you think this is less 'messy' and people agree I can change the defaults.
