### ISSUE TITLE
Inaccurate times in ALF files

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblrig#188]
I've been doing some reaction time analysis for subject 'CSHL_007' for the period of 15/03/19 to 30/04/19 and in about a third of these sessions there appear to be trials with negative reaction times.  I calculate the reaction times by subtracting `trials.goCue_times` from `trials.response_times`.

Most of these are for the first trial, however some occur elsewhere in the session.  For example, the session on 10/04/19, trial 20 has a reaction time of -0.4489 seconds.  That is, the time recorded for the goCue is 0.45 seconds later than the recorded response time.

**Comment by nbonacchi** [comment]
Can you check with the stimOnset times and response times...
Basically there is no interactive delay anymore, meaning that the command to show the stim and play the sound happen at the same time but both these outputs are independent processes and subject to the OS's scheduler delays. If the stim onset happens before the tone the subject might not wait for the go tone to respond. 
Maybe I should be waiting to detect the TTL from the sound output before allowing the wheel to move the stim.

**Comment by k1o0** [comment]
The problem seems worse when using stimOn_times.  Over two thirds of the sessions have negative reaction time trials when calculated this way.  For example during the session starting 01/04/19 trials 20, 21, 41, 140 and 329 have negative reaction times.

**Comment by nbonacchi** [comment]
I thought of creating a state to wait for the visual stim and one to wait for the tone before closing the loop. However I did not implement it because I know that in odd trials the TTL is either not sent or not registered by Bpod...

Because the timing is not guaranteed the tone could arrive before the visual stim and the mouse responds before the visual stim has a chance to flip the square color -> negative RT
or
the tone arrives after the visual stim but aslo after I close the loop. 

The order atm is show_stim, resetRE, and [play_tone, close_loop] at the same time and if the TTL of the sound never comes the task would stall...

Alternatively:
the goCue_times and the simOn_times might have NaN's and if you're dropping them you are getting the wrong ton/stim_time...

I'll look into this and get back to you.

**Comment by GaelleChapuis** [comment]
" I should be waiting to detect the TTL from the sound output before allowing the wheel to move the stim."
> Yes
" I did not implement it because I know that in odd trials the TTL is either not sent or not registered by Bpod... "
> that indicates a problem with the speaker output !  We need to know this.

That can be implemented at least in the ephys rig, where the TTL of the speaker is reliable.
