### ISSUE TITLE
Yellow window can come in before 45 min 

### ISSUE THREAD

**Issue by alejandropan** [int-brain-lab/iblrig#204]
Hey Nicco , The disengagement warning can come in before 45 min have passed (I believe this is flag no 2 -  yellow window). It would be better if the disengagement measure is only calculated after 45 min if the animal has done more than 400 trials (flag number 1).

**Comment by nbonacchi** [comment]
I could definitely add stuff to the criteria, I think Gaelle has opend an issue about stopping criteria with some decision from the WG.
As of now the code is doing what it's supposed to do: 

**_Approved stopping criteria_**
1 - less than 400 trials in 45 minutes
2 - Median response time of latest N = 20 trials > than 5 times the median response time of whole session AND more than 400 trials performed (**no time criteria**)
3 - 90 minutes elapsed since session start 

Any change or addition to the criteria should be decided in the BWG.
