### ISSUE TITLE
Lower go cue sound to 70dB

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#209]
**Is your feature request related to a problem? Please describe.**
The go cue tone is currently very loud (>80dB).
**Describe the solution you'd like**
 The Behavior WG needs a software update so that the sound is calibrated to 70 dB. We will do a trial period of 1 week to see whether mice do not drop performance.

**Comment by nbonacchi** [comment]
Hi @GaelleChapuis the value of the sound atm is 0.05 which apparently corresponds to >80db. I have no idea of the mapping between values I send to the sound card and actual DBs but I imagine you measured it somehow?
The values that the SoundCard accepts vary between 0 and 1 I selected 0.05 because it seemed quiet enough by ear, so what I would need from you is the value that you would you like the default to be?
Alternatively if you are testing something you can manually change the value in the task_settings.py file of the task you are testing with... then if everything seems fine I can change the default for everyone!

**Comment by GaelleChapuis** [comment]
Full-scale amplitude	RMS [V]	SPL [dB]
0.1	0.0418	86.40
0.2	0.0839	92.45

CCU:
0.0151 for 70.0 dB SPL

Sanworks:
0.0272 for 70.0 dB SPL

**Comment by nbonacchi** [comment]
this is for the white noise and not for the tone correct?

**Comment by GaelleChapuis** [comment]
We want to lower the volume of the tone, the white noise can stay as is.
