### ISSUE TITLE
Request: TTL test protocol for ephys

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblrig#214]
Before starting an ephys recording it would be nice if the user can check whether all the TTL pulses are coming in correctly. Therefore I propose a TTL test protocol which, flickers the sync square on the screen, presents a series of tones, and has the bpod output a bunch of pulses on the port connected to the FPGA. The user can pull up the sync channels and run the TTL protocol and observes whether all the pulses are coming in correctly before starting the recording.

**Comment by GaelleChapuis** [comment]
I vote for this but also do it more rigorously:

instead of:
The user can pull up the sync channels and run the TTL protocol and observes whether all the pulses are coming in correctly before starting the recording.

have a extraction code that is launched once the synch_test task (or whatever the name) is over, counting the number of ttl acquired on FPGA/PXI 
(i.e. have this step done by software rather than hardware)

Then, have two script: 
1- one that is automatically launched with pyBpod (like we discussed having in the training rig, with the option of selecting NO in case a mouse is already on the setup). This script will have only a few trials (so it can remain< 10 seconds)

2- one that is launched manually, with a large number of trials (e.g. 2000) - can be longer in duration. This will be launched manually to check the setup from time to time (especially after building it).

**Comment by guidomeijer** [comment]
For point 2 we can use the sync_test protocol in pyBpod, the only thing that needs to be added to the sync_test protocol is that it saves the timestamps of the Frame2TTL and audio pulses so that we can post-hoc compare them to the FPGA timestamps

**Comment by GaelleChapuis** [comment]
Related to https://github.com/int-brain-lab/iblrig/issues/222

**Comment by nbonacchi** [comment]
@guido the soon to be renamed sync_test protocol should already save data to the _iblrig_test_mouse folder I think it's the default subject I add to that test, please check if it's enough :)

**Comment by nbonacchi** [comment]
@GaelleChapuis conceptually it sounds nice, before running check if everything is working and peridically run a more extensive test to verify everything is as it should.
For point 2 I think we're OK, we can use the sync_test (soon to be renamed as per issue #239) on the ephys rig and analyze the data in cohort of the other (Arduino based) sync test

For point 1 we have a couple of problems: As per #222 launching pybpod will (optionally/like the update step) test the bpod reception of the TTL's, in some way that implicitly runs a short sync test protocol and look at the saved data if TTL count expected == TTL count read go on, otherwise tell user and don't run the app.

Alas, the ephys rig is not neatly "packed" into one single PC. Doing something similar to the behavior rig would require saving the data from the FPGA (which will require user input). transfering it to (I imagine) the local server (which also requires user_input); equally transfering the video, if we want to check for that, and the behavior data. Basically, only when all the devices have all the data together, one could run (probably requiring user input as well) a small analysis script...
I'm afraid that I don't see a way of doing this either under 10 seconds and/or without requiring as much investment from the user as running the ephys task is.  

In the protocol for running an ephys protocol there is a window of time when the cameras are running but not saving data and spikeGLX is running also not saving data, at that moment users should verify if all the inputs to the FPGA are being detected. They should move the wheel and verify if the signals are visible in the sync channels; check to see if the playing cameras are producing TTLs; play 1+ tones from the Sound Card interface and se the TTL of the sound go up and down, Create an output from BNC1Out port to test for Bpod sync using the Pybpod test IO interface; and finally open a white png file and move it in front of the sensor to se the TTL channel of the frame2TTL rise. This is a qualitative check to be sure that everything is OK before pressing REC on their devices.

**Comment by GaelleChapuis** [comment]
OK  - for point 1, let's not do it 'automatically' upon the launch of pyBpod.

Instead, let's have a protocol that :

1. Acquire Ephys data > launch video > launch Bpod task   (as is done in a regular ephys session; programs can be launched manually as usual)
2. pyBpod task  (lasting < 1 minute):
  2.1 Bonsai workflow that changes the frame2ttl synch signal G-W-B-W-B-... (G: grey, W: white, B: black) so as to have 20 W-to-B fronts
  2.2. Send 20 commands for Go cue (ON for the same duration as the go cue in the task, OFF for 300ms or however fast the sound card can be)
  2.3 Acquire rotary encoder data - experimentalists will be require to turn the wheel, clockwise and anti clockwise (making a pause at each 45 degree)


The data acquired on the FPGA will this be:
- frame2ttl for each state change of the screen
- audio TTL for each Go cue played
- camera TTL for each frame taken
- RE data

Michael S. already agered to do the analysis, so as soon as we have a pyBpod task in place we can ask experimentalists to gather a small dataset and test the protocol.

**Comment by GaelleChapuis** [comment]
We also need to check the Bpod signal (that contains the valve signal).

I thus suggest the following, for simplicity :

Change parameters in the ephys_choice_world  (rename it is ephys_choice_world_shortTest for example) so that:
- a sound is played at the beginning of each trial (as is now)
- each trial lasts max 2 seconds (change)
- the RE can be moved and data saved continuously (as is now)
- cameras acquire data (as is now)
- reward is delivered for correct trial (as is now)
- contrast is set at 100% for all trials (change) -- so the user can see
- maximum number of trials before task stops = 6 trials (change; short protocol)
- stimulus position alternates exactly, starting with left side (L-R-L-R-L-R)  (change)

Data will be saved on the FPGA and analysed as per above comment (including Bpod data).
