### ISSUE TITLE
Wheel data extraction

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblrig#298]
**Describe the bug**
Several sessions (examples EID below) only contain wheel velocity, and not times or position. We need those 2 latter variables to run the latest QC `check_wheel_angle(eid)`.

`EID_examples=['8a0cf27e-0044-4e9b-9967-4bc9ece3589b','180a2e18-c4fe-4f4d-92a2-4ff7e56ea669','84a43b9d-43d4-436c-82f1-dd804867c50c','539f6608-9ff5-41e1-b0ad-4480bdb54f15','ed763960-490d-4490-87d3-38be2985e217','fd8f339d-55d8-4aa5-a4c3-5d8f1eae852e','0e8fe973-05d0-4dfc-809e-fc48a9810bbd','61a88005-d3ff-4d9f-9615-ecf5777f8721','411f83e6-7251-435f-880b-2c4c0991f187','34273b65-92d6-49f6-8a28-434733f61e38','1457f2ff-0673-471e-894c-dbcf604653f5','6be3c374-da0b-4136-b67f-30d072670a01']
`
**To Reproduce**
Download one of the datasets above

**Expected behavior**
Have wheel times and position for all datasets available on flatiron.

**Comment by GaelleChapuis** [comment]
![major_ver](https://user-images.githubusercontent.com/43007596/70053128-0f789700-15d5-11ea-8f35-87d991b2c6f7.png)
`_ibl_trials.feedback_times.npy` is (entirely) missing for a large subset of datasets on v5 and above, even in ephysChoiceWorld !
As this dataset relies on 2 apparatus (noise + reward), it seems like the issue comes from the extraction step @nbonacchi ?

**Comment by oliche** [comment]
If it's full of NaNs it's usually because there is an issue with the BNC2 (most likely improperly connected).

I'm still in favour of preventing the experiment to proceed when BNC2 is not detected at the start. It may be annoying on the rig, but in terms of data quality and ultimately in term of the trust of the present and future analysts well, let's say we wouldn't have to have this conversation.
