### ISSUE TITLE
iblrig installation: cannot find iblrig module

### ISSUE THREAD

**Issue by karolinasocha** [int-brain-lab/iblrig#331]
After installation from scratch iblrig 
```
conda install git
cd C:\
git clone https://github.com/int-brain-lab/iblrig.git
cd iblrig
python install.py
```

I can open pyBpod GUI(v.6.4.2) but cannot run any protocol because _cannot find iblrig module_:
 
![image](https://user-images.githubusercontent.com/32096962/90661706-672c6080-e23f-11ea-91eb-7096cbac41c7.png)

**Comment by moraogando** [comment]
Hey, I'm having the same issue! did anyone find a fix? seems like a directory problem, which is strange as the folders are set up automatically..
I've tried copying the iblrig_params folder into iblrig and then loading the IBL directory as an  I get a project but then I get an "empty json file error" when I try to run a water calibration.. so I'm not sure if I'm making progress or not.

**Comment by moraogando** [comment]
update: at least for the water calibration protocol, simply appending the iblrig directory at the beginning  of the script seems to have worked just fine: 
import os, sys
sys.path.append(r'C:\iblrig')

**Comment by nbonacchi** [comment]
Looks like the installation did not run properly
try:
```
conda activate iblenv
cd C:\iblrig
pip install -e .
```
FYI: I'm working on a new install/update procedure that should fix this problem out in the next rig release...

**Comment by moraogando** [comment]
Hi there, thank you SO much for the response, I didn't have the iblenv installed at all, I was trying to create iblrig from the base (following the instructions from the paper https://www.biorxiv.org/content/biorxiv/early/2020/10/04/2020.01.17.909838.full.pdf). 

Upon installing the iblenv, and trying your suggestion, I get:

(iblenv) C:\iblrig>pip install -e .
Obtaining file:///C:/iblrig
Requirement already satisfied: cycler==0.10.0 in c:\users\adesnikdaq\.conda\envs\iblenv\lib\site-packages (from iblrig==6.4.2) (0.10.0)
ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.5.20 (from iblrig)
ERROR: No matching distribution found for opencv-python==3.4.5.20

Do you think there's a way I could fix this before the new release comes? Does this go beyond a simple path problem that can be fixed by adding sys.path.append(r'C:\iblrig')" everywhere?

**Comment by nbonacchi** [comment]
Closing this, new install procedure on Develop
