### ISSUE TITLE
additional features/bug fixes needed for iblrigv8 (for BWM)

### ISSUE THREAD

**Issue by noamroth** [int-brain-lab/iblrig#483]
1) biasedChoiceWorld needs a delay option so that we can habituate mice to a delay in the ephys rig (e.g. in iblrigv7 this was a popup window that asked how many minutes of delay you want)
2) Sometimes there are blank points for the psychometric curve and reaction times. I think for reaction times this is because the y-axis doesn't dynamically change for new data (as it did in v7), so sometimes RTs are > 4 ms and thus off the plot. For the psychometric curve I'm not sure how this happens.
3) We need a way to do water calibration, currently this isn't an option as far as I can tell?
4) biasedChoiceWorld block lines need a legend (which color corresponds to which block?) It would also be nice if the current block type was written somewhere, but this isn't absolutely necessary.
5) when one of the colored screens comes up (yellow/green/red), it would be nice to have a corresponding warning with a description of what that screen means in the powershell window - as obvious as possible would be great (e.g. as in v7, a different color, several lines of text, appearing on every trial)
6) Selection of project and task type - would be nice if this was clearer, right now it's unclear when you click or double click on the project or task whether it's selected, as when you have finished clicking there is not a different appearance
7) Flush water button - it would be nice if this changed to "flushing" when it's on, or was changed to a start/stop button instead, currently it's unclear whether it is currently running (it looks the same when it's been pressed once or twice.)

**Comment by lafresil** [comment]
Hi, 

I just wanted to underline some of the bugs/features that @noamroth mentioned:

1. Delay option/popup window is essential on the ephyschoiceworld.
2. Dynamic change of the graphs in the RT/water intake.
3. Water/Frame2TTL calibration
4. Legend of the graphs of the biased protocol. I would assume, by default, that the orange graph is the 50/50 probability but the rest I don't know. The current block type is also helpful to know.
5. It's super helpful especially in the yellow background case...
6. If when selected, the task would get a different background color instead of light gray it would be great. Now it's indeed super difficult to know which task is selected.
7. Makes things easier

Other suggestions:

1. - % of correct responses added to/instead of absolute numbers.

2. - Having:
mouse name
weight
name of the task being run

3. Add vertical and horizontal lines on graphs (at least x = 0 and y=0.5 on psychometric curve, y= 0.5 on RT).


Thank you

**Comment by noamroth** [comment]
yes thanks @lafresil! 

For (1), we use the delay for biasChoiceWorld and not ephysChoiceWorld, but probably would be best to have it for both.

**Comment by bimac** [comment]
Hey @noamroth & @lafresil, thanks for reporting these issues! I'll break them down to smaller pieces for ease of tracking:

- [ ] biasedChoiceWorld needs a delay option
- [ ] blank points for the psychometric curve and reaction time
- [ ] valve calibration
- [ ] biasedChoiceWorld block lines need a legend
- [ ] colored screens (yellow/green/red) should come with a corresponding warning in powershell
- [ ] fix background colors for selection of project and task type
- [ ] fix color scheme for flush button

**Comment by noamroth** [comment]
Great, thanks @bimac!
