### ISSUE TITLE
Seattle rig consistently failing QC

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblrig#656]
Sessions have QC outcomes such as [this](https://alyx.internationalbrainlab.org/ibl_reports/gallery/044c5966-70e4-43cd-abea-dca3bedff005/qc).  The frame2ttl has been calibration and the issue lies with the Bonsai workflow. This needs to be investigated (separate issue) and the extraction should be modified to ignore consistent sync square changes before stim on (see [#654](https://github.com/int-brain-lab/iblrig/issues/654)).

There is also an issue with the Harp sound card (see https://github.com/int-brain-lab/iblrig/issues/655). It seems particularly bad on this rig so we should investigate if the TTLs are indeed failing in the same manner, or whether it is a wiring issue. Checking Bpod and DAQ TTLs in the QC viewer will tell us more information.

**Comment by oliche** [comment]
The QC Viewer can't be run on NP2.4
This is due to the dynamic pipeline creation that attempts to recreate a pipeline after the splitting of the original probes in 4 shanks.

Here is a quick fix to address this at the QC stage, which is not desirable @mayofaulkner @k1o0  
https://github.com/int-brain-lab/ibllib/compare/taskqc?expand=1

**Comment by oliche** [comment]
This issue underwent 2 phases of mitosis and is now split in 4 issues

1. #655 Harp
2. int-brain-lab int-brain-lab/ibllib#768 task qc with np2.4
3. ephysCW v8 extracts with the wrong sequence #658
4. frame2TTL extraction and unexpected flicker before stimOn (probably due to ITI definition?) #654
