### ISSUE TITLE
pull behavioral data from Alyx, rather than local, to determine adaptive training parameters

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblrig#99]
This would allow switching between boxes (either purposefully to improve training robustness, or when one rig malfunctions)

**Comment by nbonacchi** [comment]
The rigs would need to be properly configured to use one, this way they can authenticate properly with Alyx. 
The next version of the rig code creates sessions as soon as the session ends and has a popup window to configure .one_params because of this. However if the network or Alyx are down the session fails to create. for the creation of the session record in Alyx this is OK.Users will just not be able to immediately see the weight and performance fro the Alyx interface. Nonetheless the pipeline will create the session upon registration from the local server if it has not been created already, and users will be able to see the information the next day. 

In the case of the adaptive parameters the task would not run at all if internet or Alyx are down. This is not ideal in my opininon.

If we are OK with this limitation, I should be able to easily download the raw data and settings from Alyx instead of finding it in the local data folder.

**Comment by anne-urai** [comment]
I agree it's not ideal if the task won't run without internet. Would it be possible to then 'fall-back' on local data?

**Comment by nbonacchi** [comment]
yes, however if users are rotating mice the latest local session data is certainly outdated and not the latest session the mouse did overall just the latest did on this rig...

**Comment by anne-urai** [comment]
Yes, that will be a trade-off - but in case the lab is unexpectedly without internet, you could just re-run the mouse in the same rig as yesterday.

**Comment by eejd** [comment]
I don't quite understand, I thought there was a local Alyx database not just cached in python on the rig. If the setup is: rig <-> local Alyx <-> global Alyx we are fine, as the system can default to the local database. If the local doesn't exist, we aren't registering the session from the rig anywhere except on the rig computer's raw files. I assume the Alyx transactions can be cached on a local DB and then synced up easily as they would be all independent (no concerns about collisions from other sites). Is the problem the extra engineering to manage the local DB? While I would regard internet drops as a low but non-zero probability, if the local net is down at a site and cannot be brought up with a temporary hub, it's likely there are bigger problems.... 

A solution which would be in-between would be having a local cache stored in parallel:

rig -> local DB
     -> global Alyx

so that rigs can pull from the global and fall back to the local if needed. We are presumably talking about a tiny amount of data as it's just the meta parameters? 

A final solution would be local cache on each rig, with a self-discovery based ability to communicate between the rigs; thought that's a completely novel engineering solution.

From my perspective, rotating mice would be a big big win for many many reasons. I'd suggest we at least game out the options.

**Comment by GaelleChapuis** [comment]
For ephys session, the rig has to be able to run without internet access.
